title: 개인 블로그
email: wontae.choi@mail.utoronto.ca
description: > # this means to ignore newlines until "baseurl:"
  끄적거림
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wontaechoi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: 최원태 # add your name
author-pic: 
about-author: 잘 부탁드립니다.

# Contact links
email: # Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: wontaechoi # Add your Github handle
twitter:  # Add your Twitter handle
facebook: wontaechoi # Add your Facebook handle
instagram: wntechoi # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
